# Generated by Django 5.1 on 2024-10-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_local', models.PositiveSmallIntegerField()),
                ('direccon', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('trabajadores', models.PositiveSmallIntegerField()),
                ('horarios', models.TimeField()),
                ('ambiente', models.CharField(max_length=100)),
                ('servicios', models.CharField(max_length=100)),
            ],
        ),
    ]
